# Default values for Sysdig Monitor and Secure Helm package.
global:
  clusterConfig:
    # Sets a unique name to the cluster. You can then use the cluster name to identify events using the `kubernetes.cluster.name` tag
    name: ""
  sysdig:
    # Specify your Sysdig Agent Access Key
    accessKey: ""
    # An alternative to using the Sysdig Agent access key. Specify the name of a Kubernetes secret containing an `access-key` entry
    accessKeySecret: ""
    # The SaaS region for these agents. Possible values: `"us1"`, `"us2"`, `"us3"`, `"us4"`, `"eu1"`, `"au1"`, and `"custom"`
    region: "us1"
  proxy: {}  # +doc-gen:ignore
  gke:
    # true here enables the deployment on gke autopilot clusters
    autopilot: false
    # Specifies the amount of ephemeral storage to provide to the agent container in GKE Autopilot clusters
    ephemeralStorage: "500Mi"
  image:
    # Global pull secrets
    pullSecrets: []
    # Global pull policy
    pullPolicy: IfNotPresent
  ssl:  # +doc-gen:ignore
    ca:
      # For outbound connections (secure backend, proxy,...)
      # A PEM-encoded x509 certificate.  This can also be a bundle with multiple certificates.
      certs: []
      # Example of certificate
      # certs:
      #   - |
      #       -----BEGIN CERTIFICATE-----
      #       MIIDEzCCAfugAwIBAgIQKiv9U+KxPJzu1adXwC06RzANBgkqhkiG9w0BAQsFADAU
      #       MRIwEAYDVQQDEwloYXJib3ItY2EwHhcNMjIwMjIzMDY1NjExWhcNMjMwMjIzMDY1
      #       NjExWjAUMRIwEAYDVQQDEwloYXJib3ItY2EwggEiMA0GCSqGSIb3DQEBAQUAA4IB
      #       MMNlTAQ9fvdNOTzZntye0PQYR5SR13E=
      #       -----END CERTIFICATE-----
      #   - |
      #       -----BEGIN CERTIFICATE-----
      #       MIIDEzCCAfugAwIBAgIQKiv9U+KxPJzu1adXwC06RzANBgkqhkiG9w0BAQsFADAU
      #       MRIwEAYDVQQDEwloYXJib3ItY2EwHhcNMjIwMjIzMDY1NjExWhcNMjMwMjIzMDY1
      #       NjExWjAUMRIwEAYDVQQDEwloYXJib3ItY2EwggEiMA0GCSqGSIb3DQEBAQUAA4IB
      #       MMNlTAQ9fvdNOTzZntye0PQYRTTS34D=
      #       -----END CERTIFICATE-----
      # Filename that is used when creating the secret.  Required if cert is provided.
      keyName: null
      # Provide the name of an existing Secret that contains the CA required
      existingCaSecret: null
      # Provide the filename that is defined inside the existing Secret
      existingCaSecretKeyName: null
      # Provide the name of an existing ConfigMap that contains the CA required
      existingCaConfigMap: null
      # Provide the filename that is defined inside the existing ConfigMap
      existingCaConfigMapKeyName: null
# Overrides the global namespace setting and release namespace for components
namespace: ""
image:
  # This is a hack to support RELATED_IMAGE_<identifier> feature in Helm based
  # Operators
  #
  # As long as I don't want to people to use this, I will keep it undocumented
  overrideValue: null
  # Sysdig Agent image registry
  registry: quay.io
  # Sets the image repository to pull the agent image from
  repository: sysdig/agent
  # Specifies the desired image tag
  tag: 12.18.0
  # Specifies the Image pull policy
  pullPolicy: []
  # Specifies the image pull secrets
  pullSecrets: []
# Specify a predefined resource profile.
# Options are `small`, `medium`, or `large`.
resourceProfile: small
# Allows for more fine-grained resource tuning than the resourceProfile options
resources:
  requests:
    # Specifies the CPU requested to run per pod
    cpu: ""
    # Specifies the memory requested to run per pod
    memory: ""
  limits:
    # Specifies the CPU limit per pod
    cpu: ""
    # Specifies the memory limit per pod
    memory: ""
gke:
  # true here enables the deployment on gke autopilot clusters
  autopilot: false
  # If true, required PriorityClass will be created to ensure that the agent pods are scheduled in GKE Autopilot. The parameter uses the name provided by the `priorityClassName` parameter
  createPriorityClass: false
  # Specifies the amount of ephemeral storage to provide to the agent container in GKE Autopilot clusters
  ephemeralStorage: "500Mi"
rbac:
  # true here enables creation of rbac resources
  create: true
scc:
  # true here enables creation of Security Context Constraints in Openshift
  create: true
psp:
  # true here enables creation of Pod Security Policy to allow the agent run with the required permissions
  create: true
serviceAccount:
  # Create and use serviceAccount resources
  create: true
  # Use this value as serviceAccountName
  name: null
daemonset:
  deploy: true
  # Perform rolling updates by default in the DaemonSet agent
  # ref: https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/
  updateStrategy:
    # You can also customize maxUnavailable, maxSurge or minReadySeconds if you
    # need it
    type: RollingUpdate
    rollingUpdate:
      # The maximum number of nodes with an existing available DaemonSet pod that can have an updated DaemonSet pod during an update
      maxSurge: ""
      # The maximum number of pods that can be unavailable during the update process
      maxUnavailable: ""
  ## Extra environment variables that will be pass onto deployment pods
  env: {}
  # Specifies the desired Node Selector.
  nodeSelector: {}
  # arch and os will be used to template out a node affinity block matching everything in each list. If affinity is
  # defined, these fields will be ignored
  arch:
    - amd64
    - arm64
    - s390x
  # Specifies the allowed operating systems for scheduling
  os:
    - linux
  # Specifies node affinities. Overrides daemonset.arch and daemonset.os values.
  affinity: {}
  # Allow the DaemonSet to set annotations
  annotations: {}
  # Allow the DaemonSet to set labels
  labels: {}
  # readiness probe delays
  probes:
    # Specifies the initial delay for the daemonset readiness probe
    initialDelay: 90
    # Specifies the period delay for the daemonset readiness probe
    periodDelay: 3
  kmodule:
    # Sets the environment variables for the kernel module image builder container
    env: {}
proxy:
  # Sets `http_proxy` on the agent container. Overrides the proxy setting from `global.proxy`
  httpProxy: null
  # Sets `https_proxy` on the agent container. Overrides the proxy setting from `global.proxy`
  httpsProxy: null
  # Sets `no_proxy` on the agent container. Overrides the proxy setting from `global.proxy`
  noProxy: null
# Set daemonset timezone
timezone: null
# Create the priorityClass defined below
createPriorityClass: false
# Set daemonset priorityClassName
priorityClassName: null
# Set daemonset priorityClassValue
priorityClassValue: 10
ebpf:
  # Enable eBPF support for Sysdig Agent
  enabled: false
  # Define the kind of eBPF driver that will be used by the agent. Can be `legacy_ebpf` or `universal_ebpf`
  kind: legacy_ebpf
slim:
  # Uses a slim version of the Sysdig Agent
  enabled: true
  # The image repo to be used for slim Agents
  image:
    # Specifies the slim agent image repository
    repository: sysdig/agent-slim
  # When using slim the kernel module is built in other container, which
  # contains the toolchain required to build the kernel module.
  kmoduleImage:
    # Specifies the repository to pull the kernel module image builder from
    repository: sysdig/agent-kmodule
    # Specifies the image digest to pull
    digest: null
  resources:
    # Resources required by the kernel module builder image. These are some
    # a sane defaults ones, but you can tweak or ask Sysdig Support for more
    # info about this
    requests:
      # Specifies the CPU requested for building the kernel module
      cpu: 250m
      # Specifies the memory requested for building the kernel module
      memory: 348Mi
    limits:
      # Specifies the CPU limit for building the kernel module
      cpu: 1000m
      # Specifies the memory limit for building the kernel module
      memory: 512Mi
# For Sysdig On-Prem installations or for custom collector settings, set the following fields
collectorSettings:
  # Specifies the IP address or hostname of the collector.
  collectorHost: null
  # Specifies the port number for the TCP connection of the collector service
  collectorPort: null
  # Specifies whether the collector accepts SSL
  ssl: true
  # Set this parameter to `false` if you don't want to verify SSL certificate
  sslVerifyCertificate: null
# Setting a cluster name allows you to filter events from this cluster using kubernetes.cluster.name
clusterName: ""
sysdig:
  # Required: You need your Sysdig Agent access key before running agents, either specifying 'accessKey' here, or using 'existingAccessKeySecret'
  accessKey: ""
  # Alternatively, specify the name of a Kubernetes secret containing an 'access-key' entry
  existingAccessKeySecret: ""
  # Disable capture functionality (see https://docs.sysdig.com/en/disable-captures.html)
  disableCaptures: false
  # Advanced settings. Any option in here will be directly translated into dragent.yaml in the Configmap
  settings: {}
secure:
  # true here enables Sysdig Secure: container run-time security & forensics
  enabled: true
monitor:
  # true here enables Sysdig Monitor components
  enabled: true
auditLog:
  # true here activates the K8s Audit Log feature for Sysdig Secure
  enabled: true
  # Specifies the URL where Sysdig Agent listens for the Kubernetes audit log events
  auditServerUrl: 0.0.0.0
  # Specifies the port where Sysdig Agent listens for the Kubernetes audit log events
  auditServerPort: 7765
  dynamicBackend:
    # true here configures an AuditSink who will receive the K8s audit logs
    enabled: false
# Promscrape prometheus.yaml not configured by default
prometheus:
  # Specifies the file to configure promscrape.
  file: false
  # Configures the Prometheus metric collection. Performs relabelling and filtering
  yaml: {}
extraVolumes:
  # Specifies the additional volumes to mount in the Sysdig Agent to pass new secrets or configmaps
  volumes: []
  # Specifies the mount points for additional volumes
  mounts: []
# Allows passing extra secrets that can be mounted via extraVolumes
extraSecrets: []
# Specifies the tolerations for scheduling
tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
  - effect: NoSchedule
    key: node-role.kubernetes.io/controlplane
    operator: Equal
    value: "true"
  - effect: NoExecute
    key: node-role.kubernetes.io/etcd
    operator: Equal
    value: "true"
leaderelection:
  # Enables the agent leader election algorithm
  enable: false
localForwarder:
  # Enables the Agent Local Forwarder
  enabled: false
  # Message types to forward from the Agent to the Agent Local Forwarder
  transmitMessageTypes:
    - POLICY_EVENTS
    - SECURE_AUDIT
  # List of configurations for how and where the Agent Local Forwarder should forward messages
  #
  # See https://docs.sysdig.com/en/docs/sysdig-secure/secure-events/event-forwarding/
  integrations: []
delegatedAgentDeployment:  # +doc-gen:ignore
  # Enable a specialized installation where an Agent Deployment is installed
  # in addition to the traditional DaemonSet. The DaemonSet Agents will not
  # be configured to communicate with the Kubernetes API Server, but the
  # smaller set of Agents deployed in the Deployment will. This is a specialized
  # installation type to reduce load on the Kubernetes API servers on clusters
  # with very large node counts.
  enabled: false
  delegated_nodes: -1
  deployment:
    # affinity: {}
    arch:
      - amd64
      - arm64
      - s390x
    env: {}
    os:
      - linux
    labels: {}
    # readiness probes delays
    probes:
      initialDelay: 90
      periodDelay: 3
    progressDeadlineSeconds: 600
    replicas: 1
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 384Mi
    revisionHistoryLimit: 10
    updateStrategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
# Allow direct setting of Agent log priority levels for console and file logs (info|debug)
logPriority: null
ssl:  # +doc-gen:ignore
  ca:
    # For outbound connections (secure backend, proxy,...)
    # A PEM-encoded x509 certificate.  This can also be a bundle with multiple certificates.
    certs: []
    # Example of certificate
    # certs:
    #   - |
    #       -----BEGIN CERTIFICATE-----
    #       MIIDEzCCAfugAwIBAgIQKiv9U+KxPJzu1adXwC06RzANBgkqhkiG9w0BAQsFADAU
    #       MRIwEAYDVQQDEwloYXJib3ItY2EwHhcNMjIwMjIzMDY1NjExWhcNMjMwMjIzMDY1
    #       NjExWjAUMRIwEAYDVQQDEwloYXJib3ItY2EwggEiMA0GCSqGSIb3DQEBAQUAA4IB
    #       MMNlTAQ9fvdNOTzZntye0PQYR5SR13E=
    #       -----END CERTIFICATE-----
    #   - |
    #       -----BEGIN CERTIFICATE-----
    #       MIIDEzCCAfugAwIBAgIQKiv9U+KxPJzu1adXwC06RzANBgkqhkiG9w0BAQsFADAU
    #       MRIwEAYDVQQDEwloYXJib3ItY2EwHhcNMjIwMjIzMDY1NjExWhcNMjMwMjIzMDY1
    #       NjExWjAUMRIwEAYDVQQDEwloYXJib3ItY2EwggEiMA0GCSqGSIb3DQEBAQUAA4IB
    #       MMNlTAQ9fvdNOTzZntye0PQYRTTS34D=
    #       -----END CERTIFICATE-----
    # Filename that is used when creating the secret.  Required if cert is provided.
    keyName: null
    # Provide the name of an existing Secret that contains the CA required
    existingCaSecret: null
    # Provide the filename that is defined inside the existing Secret
    existingCaSecretKeyName: null
    # Provide the name of an existing ConfigMap that contains the CA required
    existingCaConfigMap: null
    # Provide the filename that is defined inside the existing ConfigMap
    existingCaConfigMapKeyName: null
tests:  # +doc-gen:ignore
  timeout: 300s
  image:
    repo: bitnami/kubectl
    tag: 1.24.4
